version: "3.9"
services:
  vue-app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: yuba/vue-app:v01
    container_name: vitevue
    working_dir: /var/www/html/app/
    entrypoint: ["npm", "run", "dev"]
    restart: unless-stopped
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ./app/:/var/www/html/app
